### PR TITLE
Combined files "UIImage + Alpha" and "UIImage + Thumbnail" and created Swift extension.

### PR DESCRIPTION
**Pull request by rehmatqadir**

### CODE REVIEW

**Comment by rehmatqadir** [comment]
Adds methods for applying alpha to UIImages, scaling to create thumbnail.

**Comment by rehmatqadir** [comment]
@JALsnipe please review and merge

**Comment by JALsnipe** [comment]
Reviewing.

**Comment by JALsnipe** [comment]
Looks good.

**Pull request merged**
