### PR TITLE
Adding Swift NSDate Extension

### PR DESCRIPTION
**Pull request by JALsnipe**

### CODE REVIEW

**Comment by JALsnipe** [comment]
@rehmatqadir please review and test.  I found that `previousDay()` `previousDayWithoutTime()` return the same value.

**Comment by JALsnipe** [comment]
@rehmatqadir please review and merge the revised extension.

**Comment by JALsnipe** [comment]
Current result:
```
Optional(2015-06-01 22:28:00 +0000)
Optional(2015-06-01 04:00:00 +0000)
Optional(2015-06-02 04:00:00 +0000)
10:28 PM
6/2/15, 10:28 PM
June 2, 2015 at 10:28:53 PM GMT
Optional(2015-06-02 22:28:00 +0000)
now
```

**Comment by rehmatqadir** [comment]
good, will merge this.

**Pull request merged**
